import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Tasks",
  description: "Generated by create next app",
  icons: {
    icon: "/icon.png", // tu logo en public
    shortcut: "/icon.png",
    apple: "/apple-touch-icon.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="bg text-white shadow-md my-4">
          <div className="container mx-auto flex items-center justify-between px-4 py-3">
            {/* Logo y enlaces */}
            <div className="flex items-center">
              {/* Título */}
              <h1 className="text-2xl font-bold mr-6">Tasks App</h1>

              {/* Enlaces */}
              <nav className="hidden md:flex space-x-4">
                <Link
                  href="/"
                  className="hover:text-gray-300 transition-colors"
                >
                  Home
                </Link>
                <Link
                  href="/tasks"
                  className="hover:text-gray-300 transition-colors"
                >
                  Tasks
                </Link>
              </nav>
            </div>
          </div>
        </header>
        <main className="p-6">{children}</main>
        <footer className="p-4 bg text-center">
          © 2025 Tasks App with Next.js by DevEps
        </footer>
      </body>
    </html>
  );
}
